version: '3.7'
services:
  frontend:
    container_name: frontend
    ports:
      - '3000:3000'
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      WAIT_HOSTS: mysql:3306
      WAIT_HOSTS_TIMEOUT: 60
