FROM node:10.16.0

RUN npm install -g --unsafe-perm prisma2@2.0.0-preview-5

COPY . /home/app
WORKDIR /home/app

RUN npm install

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait

CMD /wait && prisma2 generate && npm start